keybindings:

  # ========================================
  # Navigation Mode - Focus and Move Windows
  # ========================================
  
  # Move focus in a given direction (left, right, up, down).
  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left"]  # Move focus to the left
  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right"]  # Move focus to the right
  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up"]  # Move focus up
  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down"]  # Move focus down
  
  # Move window in a given direction (left, right, up, down).
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]  # Move window to the left
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]  # Move window to the right
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]  # Move window up
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]  # Move window down

  # ========================================
  # Workspace Navigation Mode
  # ========================================
  
  # Focus next, previous, or recent workspace.
  - commands: ["focus --next-workspace"]
    bindings: ["alt+s"]  # Focus next workspace
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+a"]  # Focus previous workspace
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+d"]  # Focus recent workspace

  # Focus specific workspaces (1 through 9).
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]  # Focus workspace 1
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]  # Focus workspace 2
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]  # Focus workspace 3
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]  # Focus workspace 4
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]  # Focus workspace 5
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]  # Focus workspace 6
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]  # Focus workspace 7
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]  # Focus workspace 8
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]  # Focus workspace 9

  # Move window to a different workspace.
  - commands: ["move-workspace --direction left"]
    bindings: ["alt+shift+a"]  # Move window to the left workspace
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+shift+f"]  # Move window to the right workspace
  - commands: ["move-workspace --direction up"]
    bindings: ["alt+shift+d"]  # Move window to the upper workspace
  - commands: ["move-workspace --direction down"]
    bindings: ["alt+shift+s"]  # Move window to the lower workspace

  # Move window to a specific workspace and focus that workspace.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]  # Move to and focus workspace 1
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]  # Move to and focus workspace 2
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]  # Move to and focus workspace 3
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]  # Move to and focus workspace 4
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]  # Move to and focus workspace 5
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]  # Move to and focus workspace 6
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]  # Move to and focus workspace 7
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]  # Move to and focus workspace 8
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]  # Move to and focus workspace 9

  # ========================================
  # Resizing Mode
  # ========================================

  # Resize windows (width or height).
  - commands: ["resize --width -2%"]
    bindings: ["alt+u"]  # Decrease window width
  - commands: ["resize --width +2%"]
    bindings: ["alt+p"]  # Increase window width
  - commands: ["resize --height +2%"]
    bindings: ["alt+o"]  # Increase window height
  - commands: ["resize --height -2%"]
    bindings: ["alt+i"]  # Decrease window height

  # Enter the "resize" mode.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]  # Enter resize mode
  
  # ========================================
  # Tiling and Floating Mode
  # ========================================

  # Toggle between tiling and floating window layouts.
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+space"]  # Toggle floating mode (centered window)
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]  # Toggle tiling mode
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+f"]  # Toggle fullscreen mode
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]  # Toggle minimized state
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]  # Toggle tiling direction

  # ========================================
  # Window Management Mode
  # ========================================

  # Window management actions.
  - commands: ["close"]
    bindings: ["alt+shift+q"]  # Close the current window
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]  # Exit the window manager
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]  # Reload window manager config
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]  # Redraw window manager

  # Execute a command (e.g., launch a terminal or GUI).
  - commands: ["shell-exec wezterm-gui"]
    bindings: ["alt+enter"]  # Launch wezterm GUI terminal

  # ========================================
  # Pause Mode
  # ========================================

  # Enter the "pause" mode (pause all keybindings temporarily).
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]  # Enter pause mode
